# VacationPy

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from config_google import g_key

In [2]:
path = "weather_data_output.csv"

# Read the data 
weather_data = pd.read_csv(path)
weather_data

,Country,City,Latitude (Degrees),Longitude (Degrees),Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (mph)
0,TO,vaini,-21.2000,-175.2000,84.20,79,75,4.61
1,AU,esperance,-33.8667,121.9000,91.40,21,16,11.50
2,CL,punta arenas,-53.1500,-70.9167,50.00,66,90,20.71
3,RU,saskylakh,71.9167,114.0833,-20.72,85,100,14.14
4,RU,makaryev,57.8797,43.8069,-7.22,90,85,9.01
...,...,...,...,...,...,...,...,...
552,IN,mangrol,21.1167,70.1167,75.36,58,0,4.59
553,MZ,maxixe,-23.8597,35.3472,77.00,100,75,10.40
554,CI,tabou,4.4230,-7.3528,77.97,90,38,6.33
555,PE,barranca,-10.7500,-77.7667,69.64,83,0,3.98
556,CN,hanyang,32.1371,105.5126,45.00,45,99,5.99

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure